services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:4200
  server:
    build: ./server
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: your_secret_key
      DEBUG: True
      DJANGO_LOGLEVEL: info
      DJANGO_ALLOWED_HOSTS: localhost
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: tasksdb
      DATABASE_USERNAME: taskmanager
      DATABASE_PASSWORD: taskmanagerpassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
  db:
    container_name: db
    build: ./db
    restart: always
    shm_size: 128mb
    volumes: # Persistent data storage
      - data_sql:/var/lib/postgresql/data
    # The following config is purely for dev purposes, so we can access the db directly
    # This config would not be used if this were going to production!
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanagerpassword
      POSTGRES_DB: tasksdb
  task_runner:
    container_name: task_runner
    build: ./task_runner
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: tasksdb
      DATABASE_USERNAME: taskmanager
      DATABASE_PASSWORD: taskmanagerpassword
volumes:
  data_sql: