# Generated by Django 5.2.3 on 2025-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_STARTED'), (2, 'RUNNING'), (3, 'DONE'), (4, 'PAUSED'), (5, 'CANCELLED')], default=1),
        ),
    ]
