# Generated by Django 5.2.3 on 2025-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_STARTED'), (2, 'RUNNING'), (3, 'DONE'), (4, 'PAUSED'), (5, 'CANCELLED')]),
        ),
    ]
