# Generated by Django 5.2.3 on 2025-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='progressPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='results',
            field=models.TextField(default=''),
        ),
    ]
